[2022-09-28 15:39:55,055] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-28T15:39:53.897182+00:00 [queued]>
[2022-09-28 15:39:55,064] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-28T15:39:53.897182+00:00 [queued]>
[2022-09-28 15:39:55,064] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-28 15:39:55,064] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-28 15:39:55,064] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-28 15:39:55,073] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl3> on 2022-09-28 15:39:53.897182+00:00
[2022-09-28 15:39:55,078] {standard_task_runner.py:52} INFO - Started process 1865 to run task
[2022-09-28 15:39:55,081] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl3', 'spark_job_setl3', 'manual__2022-09-28T15:39:53.897182+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala3.py', '--cfg-path', '/tmp/tmps6z0hxvv', '--error-file', '/tmp/tmp3zx9j3lq']
[2022-09-28 15:39:55,082] {standard_task_runner.py:77} INFO - Job 16: Subtask spark_job_setl3
[2022-09-28 15:39:55,120] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-09-28T15:39:53.897182+00:00 [running]> on host 46d8f9f96398
[2022-09-28 15:39:55,173] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl3
AIRFLOW_CTX_TASK_ID=spark_job_setl3
AIRFLOW_CTX_EXECUTION_DATE=2022-09-28T15:39:53.897182+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-28T15:39:53.897182+00:00
[2022-09-28 15:39:55,182] {base.py:79} INFO - Using connection to: id: spark_default4. Host: spark://18584e4a1360, Port: 7077, Schema: , Login: , Password: None, extra: {'class': 'Job_s2t_AddTagVideo'}
[2022-09-28 15:39:55,184] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://18584e4a1360:7077 --jars /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-09-28 15:39:55,285] {spark_submit.py:485} INFO - JAVA_HOME is not set
[2022-09-28 15:39:55,294] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://18584e4a1360:7077 --jars /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-28 15:39:55,300] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-setl3, task_id=spark_job_setl3, execution_date=20220928T153953, start_date=20220928T153955, end_date=20220928T153955
[2022-09-28 15:39:55,309] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task spark_job_setl3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 417, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://18584e4a1360:7077 --jars /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar /home/hoaln/work/git_clone/clone_project/all_setl/new_***_spark/***-spark/spark/resources/jars/setl_2.12-1.0.0-SNAPSHOT.jar. Error code is: 1.
[2022-09-28 15:39:55,333] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-09-28 15:39:55,354] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
