[2022-10-04 04:10:42,680] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T04:10:41.827518+00:00 [queued]>
[2022-10-04 04:10:42,687] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T04:10:41.827518+00:00 [queued]>
[2022-10-04 04:10:42,687] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 04:10:42,687] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-10-04 04:10:42,687] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-10-04 04:10:42,696] {taskinstance.py:1259} INFO - Executing <Task(SparkSubmitOperator): spark_job_setl3> on 2022-10-04 04:10:41.827518+00:00
[2022-10-04 04:10:42,701] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2022-10-04 04:10:42,703] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'spark-setl3', 'spark_job_setl3', 'manual__2022-10-04T04:10:41.827518+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/spark-setl-scala3.py', '--cfg-path', '/tmp/tmpiaf2ulpx', '--error-file', '/tmp/tmpjedqs9u8']
[2022-10-04 04:10:42,704] {standard_task_runner.py:77} INFO - Job 100: Subtask spark_job_setl3
[2022-10-04 04:10:42,738] {logging_mixin.py:109} INFO - Running <TaskInstance: spark-setl3.spark_job_setl3 manual__2022-10-04T04:10:41.827518+00:00 [running]> on host e1da2cfabc67
[2022-10-04 04:10:42,779] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***admin@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark-setl3
AIRFLOW_CTX_TASK_ID=spark_job_setl3
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T04:10:41.827518+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T04:10:41.827518+00:00
[2022-10-04 04:10:42,794] {base.py:79} INFO - Using connection to: id: spark_default. Host: spark://10.0.9.226, Port: 7077, Schema: , Login: ***, Password: ***, extra: {'deploy-mode': 'cluster'}
[2022-10-04 04:10:42,795] {spark_submit.py:334} INFO - Spark-Submit cmd: spark-submit --master spark://10.0.9.226:7077 --jars hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT-jar-with-dependencies.jar --class Job_s2t_AddTagVideo --deploy-mode cluster hdfs://10.0.9.226:8020/tmp/jars/setl_2.12-1.0.0-SNAPSHOT.jar
[2022-10-04 04:10:44,447] {spark_submit.py:485} INFO - 22/10/04 04:10:44 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2022-10-04 04:10:45,355] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO SecurityManager: Changing view acls to: default
[2022-10-04 04:10:45,355] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO SecurityManager: Changing modify acls to: default
[2022-10-04 04:10:45,355] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO SecurityManager: Changing view acls groups to:
[2022-10-04 04:10:45,356] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO SecurityManager: Changing modify acls groups to:
[2022-10-04 04:10:45,356] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
[2022-10-04 04:10:45,641] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO Utils: Successfully started service 'driverClient' on port 35171.
[2022-10-04 04:10:45,696] {spark_submit.py:485} INFO - 22/10/04 04:10:45 INFO TransportClientFactory: Successfully created connection to /10.0.9.226:7077 after 32 ms (0 ms spent in bootstraps)
[2022-10-04 04:10:46,103] {spark_submit.py:485} INFO - 22/10/04 04:10:46 INFO ClientEndpoint: ... waiting before polling master for driver state
[2022-10-04 04:10:46,129] {spark_submit.py:483} INFO - identified spark driver id: driver-20221004041046-0017
[2022-10-04 04:10:46,130] {spark_submit.py:485} INFO - 22/10/04 04:10:46 INFO ClientEndpoint: Driver successfully submitted as driver-20221004041046-0017
[2022-10-04 04:10:51,141] {spark_submit.py:485} INFO - 22/10/04 04:10:51 INFO ClientEndpoint: State of driver-20221004041046-0017 is RUNNING
[2022-10-04 04:10:51,142] {spark_submit.py:485} INFO - 22/10/04 04:10:51 INFO ClientEndpoint: Driver running on 172.31.0.11:45297 (worker-20220929073136-172.31.0.11-45297)
[2022-10-04 04:10:51,142] {spark_submit.py:485} INFO - 22/10/04 04:10:51 INFO ClientEndpoint: spark-submit not configured to wait for completion, exiting spark-submit JVM.
[2022-10-04 04:10:51,146] {spark_submit.py:485} INFO - 22/10/04 04:10:51 INFO ShutdownHookManager: Shutdown hook called
[2022-10-04 04:10:51,147] {spark_submit.py:485} INFO - 22/10/04 04:10:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-6f9346fe-bcb6-4dd5-b17e-b4ca38ea8137
[2022-10-04 04:11:25,149] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._start_driver_status_tracking()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 573, in _start_driver_status_tracking
    f"Failed to poll for the driver status {max_missed_job_status_reports} times: "
airflow.exceptions.AirflowException: Failed to poll for the driver status 10 times: returncode = 1
[2022-10-04 04:11:25,157] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-setl3, task_id=spark_job_setl3, execution_date=20221004T041041, start_date=20221004T041042, end_date=20221004T041125
[2022-10-04 04:11:25,170] {standard_task_runner.py:92} ERROR - Failed to execute job 100 for task spark_job_setl3
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 433, in submit
    self._start_driver_status_tracking()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 573, in _start_driver_status_tracking
    f"Failed to poll for the driver status {max_missed_job_status_reports} times: "
airflow.exceptions.AirflowException: Failed to poll for the driver status 10 times: returncode = 1
[2022-10-04 04:11:25,196] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-10-04 04:11:25,221] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
